### ISSUE TITLE
 Calculation result issue 

### ISSUE THREAD

**Issue by leoyang-go** [TinyMPC/TinyMPC#11]
I use OSQP and TinyMPC to solve the same problem. The matrices A, B, Q, and R are all the same, but the calculated results differ significantly. Will such a problem occur? Since the LQR method is used to solve the first step

**Comment by xkhainguyen** [comment]
Hi,

Can you describe how you set up your problem?
The results can be different since we pre-process and cache the problem data based on infinite-horizon LQR as the first step.
