### ISSUE TITLE
【qustion】do you compare tinympc with hpipm?

### ISSUE THREAD

**Issue by freeclouds** [TinyMPC/TinyMPC#13]
hi, i have read tinympc relate paper "TinyMPC: Model-Predictive Control on Resource-Constrained Microcontrollers",i find in paper benchmark part,you compare tinympc with osqp,do you compare tinympc with acdos or hpipm?

**Comment by xkhainguyen** [comment]
Hi there,

We haven't compared TinyMPC with acados or hpipm yet. We hope to make it happen soon. In the meantime, we're more than happy to have that contribution from the community.

**Comment by freeclouds** [comment]
@xkhainguyen thanks your reply，i will use tinympc compare with hpipm on autodriving trajectory planning scenario, i have some problem,

1. i read the tinympc code,i find LQR parameter Pinf and Kinf usded stored data,if i use tinympc in my scenario,how to get the LQR parameters?
2.  slak variable projection in paper (17)、(18)
![linear projection](https://github.com/TinyMPC/TinyMPC/assets/19250516/ae299a27-9eee-4170-af8b-8ed29f749c2d)
,how to  derivation this two steps？i don't understand the linear projection,can you help me tell some detail? thanks a lot.

**Comment by xkhainguyen** [comment]
Hi there,

Regarding your autodriving trajectory planning scenerio, which type of car model are you using? If it's nonlinear or LTV, we're afraid we haven't officially supported them yet (you cannot obtain Kinf and Pinf -- they're derived from infinite-horizon LQR) . Meanwhile, [our another WIP repo](https://github.com/RoboticExplorationLab/TinyMPC-AL) supports bicycle LTV model.

Additionally, I've included a Julia script demonstrating how to build the model: https://github.com/xkhainguyen/tinympc-julia/blob/main/bicycle_tvlqr/bicycle5d_model.ipynb
Another script illustrates trajectory optimization to obtain the reference trajectory: https://github.com/xkhainguyen/driving-mpc/blob/main/src/rover_trajopt.jl

Regarding the projection (17) and (18), for example, if you have box constraint on the control input, the slack update becomes clamping within max and min.
