### ISSUE TITLE
Documentations on system dynamics ?

### ISSUE THREAD

**Issue by gy2256** [TinyMPC/TinyMPC#19]
Thanks for the great work. Is the system dynamics documented anywhere? 

More specifically, how is the linearized model obtained?

[https://github.com/TinyMPC/TinyMPC/blob/5c8838e557a7e2703907683985620091471859d4/examples/problem_data/quadrotor_20hz_params.hpp#L7-L33](https://github.com/TinyMPC/TinyMPC/blob/5c8838e557a7e2703907683985620091471859d4/examples/problem_data/quadrotor_20hz_params.hpp#L7-L33)

**Comment by xkhainguyen** [comment]
Hi there, 

Thank you for your questions. I hope the answers in this discussion #18 can help!

**Comment by gy2256** [comment]
Yes. It's helpful. Thanks!
