### ISSUE TITLE
Py-TinyMPC

### ISSUE THREAD

**Issue by stergiosba** [TinyMPC/TinyMPC#21]
Hey, I started working on a Python wrapper for TinyMPC for the problem setup phase using [nanobind](https://github.com/wjakob/nanobind). Would that be something that interests you?

Benefits:

- Simply no need to compile setup files since they will be in Python using `numpy.ndarrays`. Hence, files like the following will be in Python: https://github.com/TinyMPC/TinyMPC/blob/b070dfac1c3d419a01357c26fbada1d6dab09264/examples/codegen_random.cpp#L18

Drawbacks:

- Expecting minimal changes in the codebase and `CMakeFiles.txt`, mostly `const double *` to `const Eigen::MatrixXd &` in function definitions and the way `nullptr` is handled.

**Comment by xkhainguyen** [comment]
Hi there, 

Thank you for reaching out. If possible, could we take a look at your code?
We currently have a simple Python wrapper for TinyMPC at [https://github.com/TinyMPC/tinympc-python](https://github.com/TinyMPC/tinympc-python). Please take a look and suggest any potential improvements there.  We'd like any contributions in the form of pull requests. 

Best,

**Comment by stergiosba** [comment]
Hey, thanks for answering,

I have not finished the code yet, when its in a reviewable state I will do a PR.

I checked your Python Wrapper, I wouldn't go with ctypes now that there are newer tools. I am currently learning nanobind and picked your project as a test.

My target was to write the problem in python using numpy and then dispatch it to C++ for code generation. It will closely resemble the code [code_generation.py](https://github.com/TinyMPC/tinympc-python/blob/8e60a989b3a938e7a2ce3dffd2ee635fdb881ff3/tests/code_generation.py#L1) you provide in your tests in [tinympc-python](https://github.com/TinyMPC/tinympc-python).

With that being said, I had no intention of adding execution capabilities in Python, simply because its slow. I guess you just provide this as an easy verification step and not the final execution code. However, now I see that If you want to execute code in Python I think you should stay with numpy all the time, which you get in nanobind for free where with ctypes it's not straightforward. Correct me if I am wrong.

Taking a look at the following loop you have in your code, I have added 2 comments that you are probably aware of already. Again correct me if I am wrong:

```python
for i in range(NSIM):
    prob.set_x0(x, 0)
    prob.solve(0)
    prob.get_u(u, 0)
    # print(np.array(u[0]))
    x = Anp@np.array(x).reshape((n, 1))+ Bnp*np.array(u[0]) #<- Reshape is fine. Can you use numpy.asarray() here to not copy?
    # print(f"X = {x}")
    x = x.reshape(n).tolist() #<- tolist() is a copy and not a view, so its slow.
    # print(f"X = {x}")
    x_all.append(x)
print(len(x_all))
```

Best,

**Comment by xkhainguyen** [comment]
Thank you for the details!

Our aim with the high-level language wrapper is to simplify the process of setting up the problem, generating, and verifying C++ programs before deploying them on embedded platforms. Check out our [examples](https://github.com/TinyMPC/tinympc-python/tree/main/examples) to see how to use the wrapper for these purposes. Given that the primary focus is on the C++ program, the overhead in Python is likely irrelevant at this stage. Additionally, developing a native solver in Python is not currently our primary objective.

However, we'd be curious to learn about more robust and cleaner tools. We look forward to seeing your project!

**Comment by stergiosba** [comment]
Got it. So we are on the same page. Thanks!
