### ISSUE TITLE
Missing tiny_wrapper files

### ISSUE THREAD

**Issue by siddharthdeore** [TinyMPC/TinyMPC#22]
Hi Dev team,

I've noticed that the function `tiny_codegen` in [codegen.cpp](https://github.com/TinyMPC/TinyMPC/blob/6ec2a33aa62bb7d2012b37619d6b6976894c66bb/src/tinympc/codegen.cpp)  depends on files `tiny_wrapper.cpp` and the header `tiny_wrapper.hpp`, but these files are missing.

https://github.com/TinyMPC/TinyMPC/blob/6ec2a33aa62bb7d2012b37619d6b6976894c66bb/src/tinympc/codegen.cpp#L538
https://github.com/TinyMPC/TinyMPC/blob/6ec2a33aa62bb7d2012b37619d6b6976894c66bb/src/tinympc/codegen.cpp#L606

I believe they have been replaced with `tiny_api.cpp` and `tiny_api.hpp`. Therefore, I think the file names being referenced in the function should be updated accordingly. Shall I create a new pull request to address this issue?

Thanks

**Comment by sschoedel** [comment]
Hi! Sorry about that. I've been doing some refactoring to make wrappers easier to make and broke some stuff in the process. I just finished a big push that should have everything working again if you want to check it out. As of now, it should be much easier to generate code through the python wrapper (pip install tinympc). There's some examples in the tinympc-python repo and on the website to show how to use it.
